const TIMER_RUN = 'TIMER_RUN';
const TIMER_RESET = 'TIMER_RESET';
const TIMER_PAUSE = 'TIMER_PAUSE';
const TIMER_STOP = 'TIMER_STOP';
const TIMER_SET_INITIAL_TIME = 'TIMER_SET_INITIAL_TIME';
const TIMER_SET_FINAL_TIME = 'TIMER_SET_FINAL_TIME';
const TIMER_UPDATE_TIME = 'TIMER_UPDATE_TIME';

export {
  TIMER_RUN,
  TIMER_RESET,
  TIMER_PAUSE,
  TIMER_STOP,
  TIMER_SET_INITIAL_TIME,
  TIMER_SET_FINAL_TIME,
  TIMER_UPDATE_TIME,
};